[package]
name = "udp_comm_test"
version = "0.1.0"
authors = ["wredenba"]
edition = "2018"

# Cargo.toml
[dependencies]
quick-protobuf = "0.7.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
